config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }  
  resources :posts do
    resources :comments
  end

    root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

	validates :user_id, presence: true 
	validates :image, presence: true
	
	has_attached_file :image, styles: { medium: "640x >", thumb: "100x100>" },
	:storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml")
   

  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	belongs_to :user 
  	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :user_name, presence: true, length: {minimum: 4, maximum: 16}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

	def create  
	  @comment = @post.comments.build(comment_params)
	  @comment.user_id = current_user.id

	  if @comment.save
	    flash[:success] = "You commented the hell out of that post!"
	    redirect_to :back
	  else
	    flash[:alert] = "Check the comment form, something went horribly wrong."
	    render root_path
	  end
	end

	def destroy  
	  @comment = @post.comments.find(params[:id])

	  @comment.destroy
	  flash[:success] = "Comment deleted :("
	  redirect_to root_path
	end
private
	def comment_params  
	  params.require(:comment).permit(:content)
	end

	def set_post  
	  @post = Post.find(params[:post_id])
	end  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :owned_post, only: [:edit, :update, :destroy]  

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:caption, :image)
    end

    def owned_post  
      unless current_user == @post.user
        flash[:alert] = "That post doesn't belong to you!"
        redirect_to root_path
      end
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">#ProjectCasting</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'New Post', new_post_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>  
          <li><%= link_to 'Register', new_user_registration_path %></li>  
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectCasting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class = "container">
		<%= yield %>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, url: posts_path, html: {multipart: true}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.file_field :image, class: 'form-control' %>
    <h3><%= f.label :caption %></h3>
    <%= f.text_area :caption, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link' %>
|
<%= link_to 'Back', @post, class: 'btn btn-link' %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Electronic Press Kit</h1>



  

  <div class="row posts-wrapper"> 
    <% @posts.each do |post| %>
        <div class="post">
          <div class="post-head">
            <div class="name">
              <p><%= post.user.user_name %></p>
            </div>
          </div>
          <div class="image center-block">
            <%= link_to (image_tag(post.image.url(:medium),class: 'img-responsive')), post %>
          </div>
          <div class="post-bottom">
            <div class= "caption">
              <div class= "name">
                <%= post.user.user_name %>
              </div>
              <%= post.caption %>
              <% if post.comments %>
                <% post.comments.each do |comment| %>
                  <div class="comment">
                    <div class="name">
                      <%= comment.user.user_name %>
                    </div>
                    <div class="comment-content">
                      <p><%= comment.content %></p>
                      <% if comment.user == current_user %>
                        <%= link_to post_comment_path(post, comment), method: :delete, data: {confirm: "Are you sure?"} %>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
              <div class="comment-form">
                <%= form_for [post, post.comments.new] do |f| %>
                  <%= f.text_field :content, placeholder: 'Add a comment...' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
     <% end %>
  </div>   

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path, class: 'btn btn-link' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

	<div class="row posts-wrapper">
		<div class="post">
			<div class="post-head">
				<div class="name">
					<p><%= @post.user.user_name %></p>
				</div>
			</div>
			<div class="image center-block">
				<%= image_tag @post.image.url(:medium),class: 'img-responsive' %>
			</div>
			<p class= "caption">
		  		<%= @post.caption %>
		  	</p>
		  	<% if @post.user.id == current_user.id %>
		  		<%= link_to 'Back', posts_path, class: 'btn btn-link, center-block' %>
			  	<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-link' %>
			<% else %>
				<%= link_to 'Back', posts_path, class: 'btn btn-link, center-block' %>
			<% end %>
	  	</div>
	</div>